name: Erlang CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Test on ${{ matrix.os }} with OTP ${{ matrix.otp }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        otp: [22, 23, 24, 25]
        os: [ubuntu-latest, macos-latest]
        # OTP lower than 23 does not run on ubuntu-latest (22.04), see
        # https://github.com/erlef/setup-beam#compatibility-between-operating-system-and-erlangotp
        exclude:
          - otp: 22
            os: ubuntu-latest
          - otp: 23
            os: ubuntu-latest
        include:
          - otp: 22
            os: ubuntu-20.04
          - otp: 23
            os: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies (Linux)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install libsnappy-dev libc6-dev
      - name: Install Dependencies (OSX)
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          export majorversion="$(cut -d '.' -f 1 <<< "${{ matrix.otp }}")"
          brew install coreutils erlang@$majorversion snappy
          echo "/usr/local/opt/erlang@$majorversion/bin" >> $GITHUB_PATH
      - name: Install Erlang/OTP
        # setup beam doesn't provide MacOS packages
        # we use Homebrew to instal them
        if: ${{ !startsWith(matrix.os , 'macos') }}
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
      - name: Compile
        run: ./rebar3 compile
      - name: Run xref and dialyzer
        run: ./rebar3 do xref, dialyzer
      - name: Run tests
        run: ./rebar3 as gha do eunit
